services:
  - type: web
    name: slacko-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: DATABASE_URL
        fromDatabase:
          name: slacko-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: slacko-redis
          property: connectionString
      - key: ALLOWED_HOSTS
        value: slacko-api.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://slacko-api.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://slacko-api.onrender.com
      - key: FRONTEND_BASE_URL
        value: https://slacko-api.onrender.com
      - key: GEMINI_API_KEY
        sync: false

  - type: postgres
    name: slacko-db
    plan: free

  - type: keyvalue
    name: slacko-redis
    plan: free
    ipAllowList: []
